/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsTroubleshootingRouteImport } from './routes/docs.troubleshooting'
import { Route as DocsSecurityRouteImport } from './routes/docs.security'
import { Route as DocsOauthRouteImport } from './routes/docs.oauth'
import { Route as DocsMigrationRouteImport } from './routes/docs.migration'
import { Route as DocsGettingStartedRouteImport } from './routes/docs.getting-started'
import { Route as DocsFaqRouteImport } from './routes/docs.faq'
import { Route as DocsContributingRouteImport } from './routes/docs.contributing'
import { Route as DocsChangelogRouteImport } from './routes/docs.changelog'
import { Route as DocsBestPracticesRouteImport } from './routes/docs.best-practices'
import { Route as DocsArchitectureRouteImport } from './routes/docs.architecture'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTroubleshootingRoute = DocsTroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSecurityRoute = DocsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DocsRoute,
} as any)
const DocsOauthRoute = DocsOauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMigrationRoute = DocsMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRoute,
} as any)
const DocsContributingRoute = DocsContributingRouteImport.update({
  id: '/contributing',
  path: '/contributing',
  getParentRoute: () => DocsRoute,
} as any)
const DocsChangelogRoute = DocsChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBestPracticesRoute = DocsBestPracticesRouteImport.update({
  id: '/best-practices',
  path: '/best-practices',
  getParentRoute: () => DocsRoute,
} as any)
const DocsArchitectureRoute = DocsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRouteWithChildren
  '/examples': typeof ExamplesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/launch': typeof LaunchRoute
  '/playground': typeof PlaygroundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/best-practices': typeof DocsBestPracticesRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/contributing': typeof DocsContributingRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/migration': typeof DocsMigrationRoute
  '/docs/oauth': typeof DocsOauthRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/auth': typeof AuthRoute
  '/examples': typeof ExamplesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/launch': typeof LaunchRoute
  '/playground': typeof PlaygroundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/best-practices': typeof DocsBestPracticesRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/contributing': typeof DocsContributingRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/migration': typeof DocsMigrationRoute
  '/docs/oauth': typeof DocsOauthRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/api': typeof ApiRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRouteWithChildren
  '/examples': typeof ExamplesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/launch': typeof LaunchRoute
  '/playground': typeof PlaygroundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/best-practices': typeof DocsBestPracticesRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/contributing': typeof DocsContributingRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/migration': typeof DocsMigrationRoute
  '/docs/oauth': typeof DocsOauthRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/auth'
    | '/docs'
    | '/examples'
    | '/forgot-password'
    | '/launch'
    | '/playground'
    | '/reset-password'
    | '/dashboard'
    | '/docs/architecture'
    | '/docs/best-practices'
    | '/docs/changelog'
    | '/docs/contributing'
    | '/docs/faq'
    | '/docs/getting-started'
    | '/docs/migration'
    | '/docs/oauth'
    | '/docs/security'
    | '/docs/troubleshooting'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/auth'
    | '/examples'
    | '/forgot-password'
    | '/launch'
    | '/playground'
    | '/reset-password'
    | '/dashboard'
    | '/docs/architecture'
    | '/docs/best-practices'
    | '/docs/changelog'
    | '/docs/contributing'
    | '/docs/faq'
    | '/docs/getting-started'
    | '/docs/migration'
    | '/docs/oauth'
    | '/docs/security'
    | '/docs/troubleshooting'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/api'
    | '/auth'
    | '/docs'
    | '/examples'
    | '/forgot-password'
    | '/launch'
    | '/playground'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/docs/architecture'
    | '/docs/best-practices'
    | '/docs/changelog'
    | '/docs/contributing'
    | '/docs/faq'
    | '/docs/getting-started'
    | '/docs/migration'
    | '/docs/oauth'
    | '/docs/security'
    | '/docs/troubleshooting'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiRoute: typeof ApiRoute
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRouteWithChildren
  ExamplesRoute: typeof ExamplesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LaunchRoute: typeof LaunchRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/troubleshooting': {
      id: '/docs/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/docs/troubleshooting'
      preLoaderRoute: typeof DocsTroubleshootingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/security': {
      id: '/docs/security'
      path: '/security'
      fullPath: '/docs/security'
      preLoaderRoute: typeof DocsSecurityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/oauth': {
      id: '/docs/oauth'
      path: '/oauth'
      fullPath: '/docs/oauth'
      preLoaderRoute: typeof DocsOauthRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/migration': {
      id: '/docs/migration'
      path: '/migration'
      fullPath: '/docs/migration'
      preLoaderRoute: typeof DocsMigrationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/contributing': {
      id: '/docs/contributing'
      path: '/contributing'
      fullPath: '/docs/contributing'
      preLoaderRoute: typeof DocsContributingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/changelog': {
      id: '/docs/changelog'
      path: '/changelog'
      fullPath: '/docs/changelog'
      preLoaderRoute: typeof DocsChangelogRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/best-practices': {
      id: '/docs/best-practices'
      path: '/best-practices'
      fullPath: '/docs/best-practices'
      preLoaderRoute: typeof DocsBestPracticesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/architecture': {
      id: '/docs/architecture'
      path: '/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsArchitectureRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DocsRouteChildren {
  DocsArchitectureRoute: typeof DocsArchitectureRoute
  DocsBestPracticesRoute: typeof DocsBestPracticesRoute
  DocsChangelogRoute: typeof DocsChangelogRoute
  DocsContributingRoute: typeof DocsContributingRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsMigrationRoute: typeof DocsMigrationRoute
  DocsOauthRoute: typeof DocsOauthRoute
  DocsSecurityRoute: typeof DocsSecurityRoute
  DocsTroubleshootingRoute: typeof DocsTroubleshootingRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsArchitectureRoute: DocsArchitectureRoute,
  DocsBestPracticesRoute: DocsBestPracticesRoute,
  DocsChangelogRoute: DocsChangelogRoute,
  DocsContributingRoute: DocsContributingRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsMigrationRoute: DocsMigrationRoute,
  DocsOauthRoute: DocsOauthRoute,
  DocsSecurityRoute: DocsSecurityRoute,
  DocsTroubleshootingRoute: DocsTroubleshootingRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiRoute: ApiRoute,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRouteWithChildren,
  ExamplesRoute: ExamplesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LaunchRoute: LaunchRoute,
  PlaygroundRoute: PlaygroundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
